forum/apps/accounts/urls.py
from django.urls import path

from . import views

app_name = 'accounts'
urlpatterns = [
	path('register/', views.register, name = 'register'),
	path('login/', views.user_login, name = 'login'),
	path('logout/', views.user_logout, name = 'logout'),
	path('profile/', views.profile, name = 'profile'),
	path('my_posts/', views.my_posts, name = 'my_posts'),
	path('my_comments/', views.my_comments, name = 'my_comments'),
]

forum/apps/topics/urls.py
from django.urls import path

from . import views

app_name = 'topics'
urlpatterns = [
	path('', views.index, name = 'index'),
	path('post/', views.post, name = 'post'),
	path('<int:topic_id>/delete_post/', views.delete_post, name = 'delete_post'),
	path('create_post/', views.create_post, name = 'create_post'),
	path('<int:topic_id>/', views.detail, name = 'detail'),
	path('<int:topic_id>/leave_comment/', views.leave_comment, name = 'leave_comment'),
	path('<int:topic_id>/delete_comment/<int:c_id>', views.delete_comment, name = 'delete_comment'),
]

forum/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
	path('', include('topics.urls')),
    path('accounts/', include('accounts.urls')),
    path('admin/', admin.site.urls),
]

forum/apps/accounts/models.py
from django.db import models
# Create your models here.

forum/apps/topics/models.py
from django.db import models
from django.contrib.auth.models import User


class Topic(models.Model):
    topic_title = models.CharField('Title', max_length=200, default='')
    topic_text = models.TextField('Text', default='')
    author_id = models.IntegerField('Id', default=0)
    topic_subject = models.TextField('options', default='')

    def __str__(self):
        return self.topic_title

    class Meta:
        verbose_name = 'Topic'
        verbose_name_plural = 'Topics'


class Comment(models.Model):
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    author_name = models.CharField('Name', max_length=20, default='')
    comment_text = models.CharField('Text', max_length=200, default='')
    author_id = models.IntegerField('Id', default=0)

    def __str__(self):
        return self.comment_text

    class Meta:
        verbose_name = 'Comment'
        verbose_name_plural = 'Comments'

forum/apps/accounts/forms.py
from django import forms

from django.contrib.auth.forms import UserCreationForm, AuthenticationForm


class UserLoginForm(AuthenticationForm):
	username = forms.CharField(label='', widget=forms.TextInput(attrs={'class': 'form-label-group', 'class': 'form-control', 'placeholder': 'Псевдоним'}))
	password = forms.CharField(label='', widget=forms.PasswordInput(attrs={'class': 'form-label-group', 'class': 'form-control', 'placeholder': 'Пароль'}))

class UserRegisterForm(UserCreationForm):
	username = forms.CharField(label='', widget=forms.TextInput(attrs={'class': 'form-label-group', 'class': 'form-control', 'placeholder': 'Псевдоним'}))
	password1 = forms.CharField(label='', widget=forms.PasswordInput(attrs={'class': 'form-label-group', 'class': 'form-control', 'placeholder': 'Пароль'}))
	password2 = forms.CharField(label='', widget=forms.PasswordInput(attrs={'class': 'form-label-group', 'class': 'form-control', 'placeholder': 'Повтор пароля'}))

forum/apps/accounts/views.py
from django.http import Http404, HttpResponseRedirect
from django.shortcuts import render, redirect
from django.urls import reverse

from .forms import UserRegisterForm, UserLoginForm
from django.contrib import messages
from django.contrib.auth import login, logout
from topics.models import Topic, Comment


def profile(request):
    if not request.user.is_authenticated:
        raise Http404("Статья не найдена!")
    return render(request, 'accounts/profile.html')


def user_login(request):
    if request.method == 'POST':
        form = UserLoginForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            return redirect('/')
    else:
        form = UserLoginForm()
    return render(request, 'accounts/login.html', {'form': form})


def register(request):
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Регистрация прошла успешно')
            return redirect('accounts:login')
        else:
            messages.error(request, 'Произошла ошибка')
    else:
        form = UserRegisterForm()
    return render(request, 'accounts/register.html', {"form": form})


def user_logout(request):
    logout(request)
    return redirect('accounts:login')


def my_posts(request):
    if not request.user.is_authenticated:
        raise Http404("Страница не найдена!")

    try:
        topic = Topic.objects.filter(author_id=request.user.id)
    except:
        raise Http404("Статьи не найдены!")

    return render(request, 'accounts/my_posts.html', {"topic": topic})

def my_comments(request):
    if not request.user.is_authenticated:
        raise Http404("Страница не найдена!")

    try:
        comment = Comment.objects.filter(author_id=request.user.id)
    except:
        raise Http404("Статьи не найдены!")

    return render(request, 'accounts/my_comments.html', {"comment": comment, "noVolume": False})

forum/apps/topics/views.py
from django.contrib.auth.models import User
from django.http import Http404, HttpResponseRedirect, HttpResponse
from django.shortcuts import render, redirect
from django.urls import reverse

from .models import Topic, Comment


def index(request):
    latest_topics_list = Topic.objects.order_by('-id')
    return render(request, 'topics/list.html', {'latest_topics_list': latest_topics_list})


def post(request):
    if request.user.is_authenticated:
        return render(request, 'topics/post.html')
    raise Http404("Статья не найдена!")


def create_post(request):
    if request.user.is_authenticated:
        try:
            topic = Topic(topic_title=request.POST['title'], topic_text=request.POST['text'],
                          author_id=request.user.id, topic_subject=request.POST['options'])
        except:
            topic = Topic(topic_title=request.POST['title'], topic_text=request.POST['text'],
                          author_id=request.user.id, topic_subject='ФЛУД')
        topic.save()
    return HttpResponseRedirect('/')


def detail(request, topic_id):
    try:
        topic = Topic.objects.get(id=topic_id)
        name = User.objects.get(id=topic.author_id)

    except:
        raise Http404("Статья не найдена!")
    latest_comments_list = topic.comment_set.order_by('id')
    return render(request, 'topics/detail.html',
                  {'topic': topic, 'latest_comments_list': latest_comments_list, 'name': name})


def leave_comment(request, topic_id):
    try:
        topic = Topic.objects.get(id=topic_id)
    except:
        raise Http404("Статья не найдена!")
    if request.user.is_authenticated:
        topic.comment_set.create(author_name=request.user, comment_text=request.POST['text'], author_id=request.user.id)
    return HttpResponseRedirect(reverse('topics:detail', args=(topic.id,)))


def delete_post(request, topic_id):
    try:
        topic = Topic.objects.get(id=topic_id)
        if request.user.is_authenticated and request.user.id == topic.author_id or request.user.is_staff == 1:
            topic.delete()
            return HttpResponseRedirect('/')
        else:
            raise Http404("Статья не найдена!")
    except:
        raise Http404("Статья не найдена!")


def delete_comment(request, topic_id, c_id):
    if topic_id != False:
        try:
            topic = Topic.objects.get(id=topic_id)
            comment = Comment.objects.get(id=c_id)
            print(comment)
            if request.user.is_authenticated and request.user.id == comment.author_id or request.user.is_staff == 1:
                comment.delete()
                return HttpResponseRedirect(reverse('topics:detail', args=(topic.id,)))
            else:

                print("Обшибка 1")
                raise Http404("Статья не найдена!")

        except:
            raise Http404("Статья не найдена!")
            print("Обшибка 2")
    else:
        try:
            comment = Comment.objects.get(id=c_id)
            print(comment)
            if request.user.is_authenticated and request.user.id == comment.author_id or request.user.is_staff == 1:
                comment.delete()
                return HttpResponseRedirect(reverse('accounts:my_comments'))
            else:

                print("Обшибка 1")
                raise Http404("Статья не найдена!")

        except:
            raise Http404("Статья не найдена!")
            print("Обшибка 2")

forum/templates/accounts/my_comments.html
{% extends 'base.html' %} &nbsp;{% block content %}
<br>
<h3>Мои комменты:</h3>
{% if comment %}
	{% for c in comment %}

		<p>
			<strong>{{c.author_name}}
				{% if request.user.is_authenticated %}
		{% if request.user.id == c.author_id %}

			<a class="btn btn-link" title="Удалить" href="{% url 'accounts:delete_comment' noVolume c.id %}">
				<svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-x-circle" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
				  <path fill-rule="evenodd" d="M8 15A7 7 0 1 0 8 1a7 7 0 0 0 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z"/>
				  <path fill-rule="evenodd" d="M11.854 4.146a.5.5 0 0 1 0 .708l-7 7a.5.5 0 0 1-.708-.708l7-7a.5.5 0 0 1 .708 0z"/>
				  <path fill-rule="evenodd" d="M4.146 4.146a.5.5 0 0 0 0 .708l7 7a.5.5 0 0 0 .708-.708l-7-7a.5.5 0 0 0-.708 0z"/>
				</svg>
			</a>
		{% endif %}
	{% endif %}</strong>
			<p>{{c.comment_text}}</p>
		</p>
	{% endfor %}
{% else %}

<p>Нет комментариев :(</p>

{% endif %}

{% endblock content %}

forum/templates/accounts/my_posts.html
{% extends 'base.html' %} &nbsp;{% block content %}
<br>
<h3>Мои посты:</h3>
{% if topic %}
        {% for a in topic %}

			<div class="media text-muted pt-3">
				<img data-src="holder.js/32x32?theme=thumb&amp;bg=007bff&amp;fg=007bff&amp;size=1" alt="32x32" class="mr-2 rounded" style="width: 32px; height: 32px;" src="data:image/svg+xml;charset=UTF-8,%3Csvg%20width%3D%2232%22%20height%3D%2232%22%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20viewBox%3D%220%200%2032%2032%22%20preserveAspectRatio%3D%22none%22%3E%3Cdefs%3E%3Cstyle%20type%3D%22text%2Fcss%22%3E%23holder_177cf5504d3%20text%20%7B%20fill%3A%23007bff%3Bfont-weight%3Abold%3Bfont-family%3AArial%2C%20Helvetica%2C%20Open%20Sans%2C%20sans-serif%2C%20monospace%3Bfont-size%3A2pt%20%7D%20%3C%2Fstyle%3E%3C%2Fdefs%3E%3Cg%20id%3D%22holder_177cf5504d3%22%3E%3Crect%20width%3D%2232%22%20height%3D%2232%22%20fill%3D%22%23007bff%22%3E%3C%2Frect%3E%3Cg%3E%3Ctext%20x%3D%2212.291666746139526%22%20y%3D%2216.999999976158144%22%3E32x32%3C%2Ftext%3E%3C%2Fg%3E%3C%2Fg%3E%3C%2Fsvg%3E" data-holder-rendered="true">
			  <p class="media-body pb-3 mb-0 small lh-125 border-bottom border-gray">
				<strong class="d-block text-gray-dark"><a href="{% url 'topics:detail' a.id %}">{{a.topic_title}}</a></strong>
					#{{a.topic_subject}}
			  </p>
			{% if request.user.id == a.author_id %}
				<a class="btn btn-link" title="Удалить" href="{% url 'topics:delete_post' a.id %}">
					<svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-x-circle" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
					  <path fill-rule="evenodd" d="M8 15A7 7 0 1 0 8 1a7 7 0 0 0 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z"/>
					  <path fill-rule="evenodd" d="M11.854 4.146a.5.5 0 0 1 0 .708l-7 7a.5.5 0 0 1-.708-.708l7-7a.5.5 0 0 1 .708 0z"/>
					  <path fill-rule="evenodd" d="M4.146 4.146a.5.5 0 0 0 0 .708l7 7a.5.5 0 0 0 .708-.708l-7-7a.5.5 0 0 0-.708 0z"/>
					</svg>
				</a>
			{% endif %}
			</div>

        {% endfor %}
{% endif %}

{% endblock content %}

forum/templates/accounts/profile.html
{% extends 'base.html' %} &nbsp;{% block content %}

<br>
<h4>Добро пожаловать, <em style = "color: blue;">{{request.user.username}}!</em> Чего изволите?</h4>
<br>
<h5 style = "color: green;">>> Сменить псевдоним</h5>
<h5 style = "color: green;">>> Сменить пароль</h5>
<h5 style = "color: green;">>> Удалить профиль</h5>
<br>
<h4>Просмотреть:</h4>
<br>
<a href = "{% url 'accounts:my_posts' %}">Публикации</a>
<a href = "{% url 'accounts:my_comments' %}">Комментарии</a>

{% endblock content %}

forum/templates/topics/detail.html
{% extends 'base.html' %}

<title>{% block title %}{{topic.topic_title}}{% endblock %}</title>

{% block content %}

<br>

<h6>Автор: @{{name.username}}
	{% if request.user.is_authenticated %}
			<a class="btn btn-link" title="Жаловаться" href="{% url 'topics:delete_post' topic.id %}">
				<svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-flag" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
				  <path fill-rule="evenodd" d="M3.5 1a.5.5 0 0 1 .5.5v13a.5.5 0 0 1-1 0v-13a.5.5 0 0 1 .5-.5z"/>
				  <path fill-rule="evenodd" d="M3.762 2.558C4.735 1.909 5.348 1.5 6.5 1.5c.653 0 1.139.325 1.495.562l.032.022c.391.26.646.416.973.416.168 0 .356-.042.587-.126a8.89 8.89 0 0 0 .593-.25c.058-.027.117-.053.18-.08.57-.255 1.278-.544 2.14-.544a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-.5.5c-.638 0-1.18.21-1.734.457l-.159.07c-.22.1-.453.205-.678.287A2.719 2.719 0 0 1 9 9.5c-.653 0-1.139-.325-1.495-.562l-.032-.022c-.391-.26-.646-.416-.973-.416-.833 0-1.218.246-2.223.916a.5.5 0 1 1-.515-.858C4.735 7.909 5.348 7.5 6.5 7.5c.653 0 1.139.325 1.495.562l.032.022c.391.26.646.416.973.416.168 0 .356-.042.587-.126.187-.068.376-.153.593-.25.058-.027.117-.053.18-.08.456-.204 1-.43 1.64-.512V2.543c-.433.074-.83.234-1.234.414l-.159.07c-.22.1-.453.205-.678.287A2.719 2.719 0 0 1 9 3.5c-.653 0-1.139-.325-1.495-.562l-.032-.022c-.391-.26-.646-.416-.973-.416-.833 0-1.218.246-2.223.916a.5.5 0 0 1-.554-.832l.04-.026z"/>
				</svg>
			</a>
		{% if request.user.id == topic.author_id or request.user.is_staff == 1 %}

			<a class="btn btn-link" title="Удалить" href="{% url 'topics:delete_post' topic.id %}">
				<svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-x-circle" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
				  <path fill-rule="evenodd" d="M8 15A7 7 0 1 0 8 1a7 7 0 0 0 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z"/>
				  <path fill-rule="evenodd" d="M11.854 4.146a.5.5 0 0 1 0 .708l-7 7a.5.5 0 0 1-.708-.708l7-7a.5.5 0 0 1 .708 0z"/>
				  <path fill-rule="evenodd" d="M4.146 4.146a.5.5 0 0 0 0 .708l7 7a.5.5 0 0 0 .708-.708l-7-7a.5.5 0 0 0-.708 0z"/>
				</svg>
			</a>
		{% endif %}
	{% endif %}
</h6>


<div class = "text-center">
	<h5>{{topic.topic_title}}</h5>
</div>
<hr>
<div class = "" style = "padding-left: 10px; padding-right: padding-top: 20px;">
	<p>{{topic.topic_text}}</p>
</div>
<hr>



{% if latest_comments_list %}
	{% for c in latest_comments_list %}

		<p>
			<strong>{{c.author_name}}{% if request.user.is_authenticated %}
			<a class="btn btn-link" title="Жаловаться" href="{% url 'topics:delete_comment' topic.id c.id %}">
				<svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-flag" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
				  <path fill-rule="evenodd" d="M3.5 1a.5.5 0 0 1 .5.5v13a.5.5 0 0 1-1 0v-13a.5.5 0 0 1 .5-.5z"/>
				  <path fill-rule="evenodd" d="M3.762 2.558C4.735 1.909 5.348 1.5 6.5 1.5c.653 0 1.139.325 1.495.562l.032.022c.391.26.646.416.973.416.168 0 .356-.042.587-.126a8.89 8.89 0 0 0 .593-.25c.058-.027.117-.053.18-.08.57-.255 1.278-.544 2.14-.544a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-.5.5c-.638 0-1.18.21-1.734.457l-.159.07c-.22.1-.453.205-.678.287A2.719 2.719 0 0 1 9 9.5c-.653 0-1.139-.325-1.495-.562l-.032-.022c-.391-.26-.646-.416-.973-.416-.833 0-1.218.246-2.223.916a.5.5 0 1 1-.515-.858C4.735 7.909 5.348 7.5 6.5 7.5c.653 0 1.139.325 1.495.562l.032.022c.391.26.646.416.973.416.168 0 .356-.042.587-.126.187-.068.376-.153.593-.25.058-.027.117-.053.18-.08.456-.204 1-.43 1.64-.512V2.543c-.433.074-.83.234-1.234.414l-.159.07c-.22.1-.453.205-.678.287A2.719 2.719 0 0 1 9 3.5c-.653 0-1.139-.325-1.495-.562l-.032-.022c-.391-.26-.646-.416-.973-.416-.833 0-1.218.246-2.223.916a.5.5 0 0 1-.554-.832l.04-.026z"/>
				</svg>
			</a>
		{% if request.user.id == c.author_id or request.user.is_staff == 1 %}

			<a class="btn btn-link" title="Удалить" href="{% url 'topics:delete_comment' topic.id c.id %}">
				<svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-x-circle" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
				  <path fill-rule="evenodd" d="M8 15A7 7 0 1 0 8 1a7 7 0 0 0 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z"/>
				  <path fill-rule="evenodd" d="M11.854 4.146a.5.5 0 0 1 0 .708l-7 7a.5.5 0 0 1-.708-.708l7-7a.5.5 0 0 1 .708 0z"/>
				  <path fill-rule="evenodd" d="M4.146 4.146a.5.5 0 0 0 0 .708l7 7a.5.5 0 0 0 .708-.708l-7-7a.5.5 0 0 0-.708 0z"/>
				</svg>
			</a>
		{% endif %}
	{% endif %}</strong>
			<p>{{c.comment_text}}</p>
		</p>
	{% endfor %}
{% else %}

<p>Нет комментариев :(</p>

{% endif %}

{% if request.user.is_authenticated %}
<form action = "{% url 'topics:leave_comment' topic.id %}" method ="POST">
	{% csrf_token %}
	<textarea  style="height: 100px;" class="form-control" name="text" required="" placeholder="Текст комментария" cols="30" rows="10"></textarea><br>
	<button type = "submit">Отправить</button>
</form>

{% else %}
<a href="{% url 'accounts:login' %}">Войдите</a> или <a href="{% url 'accounts:register' %}">зарегистрируйтесь</a>, чтобы оставить комментарий.
{% endif %}

{% endblock %}

forum/templates/topics/list.html
{% extends 'base.html' %}

{% block title %}МБ{% endblock %}

{% block content %}


		<div class="my-3 p-3 bg-white rounded box-shadow">

			<h5>«Статьи»</h5>

			<hr>

			{% if latest_topics_list %}
					{% for a in latest_topics_list %}

			<div class="media text-muted pt-3">
				<img data-src="holder.js/32x32?theme=thumb&amp;bg=007bff&amp;fg=007bff&amp;size=1" alt="32x32" class="mr-2 rounded" style="width: 32px; height: 32px;" src="data:image/svg+xml;charset=UTF-8,%3Csvg%20width%3D%2232%22%20height%3D%2232%22%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20viewBox%3D%220%200%2032%2032%22%20preserveAspectRatio%3D%22none%22%3E%3Cdefs%3E%3Cstyle%20type%3D%22text%2Fcss%22%3E%23holder_177cf5504d3%20text%20%7B%20fill%3A%23007bff%3Bfont-weight%3Abold%3Bfont-family%3AArial%2C%20Helvetica%2C%20Open%20Sans%2C%20sans-serif%2C%20monospace%3Bfont-size%3A2pt%20%7D%20%3C%2Fstyle%3E%3C%2Fdefs%3E%3Cg%20id%3D%22holder_177cf5504d3%22%3E%3Crect%20width%3D%2232%22%20height%3D%2232%22%20fill%3D%22%23007bff%22%3E%3C%2Frect%3E%3Cg%3E%3Ctext%20x%3D%2212.291666746139526%22%20y%3D%2216.999999976158144%22%3E32x32%3C%2Ftext%3E%3C%2Fg%3E%3C%2Fg%3E%3C%2Fsvg%3E" data-holder-rendered="true">
			  <p class="media-body pb-3 mb-0 small lh-125 border-bottom border-gray">
				<strong class="d-block text-gray-dark"><a href="{% url 'topics:detail' a.id %}">{{a.topic_title}}</a></strong>
					#новости #истина #путин #навальный #NFSM
			  </p>
			</div>

					{% endfor %}
				{% else %}
					Статьи не найдены :(
			{% endif %}

			<small class="d-block text-right mt-3">
			  <a href="#">All updates</a>
			</small>
      	</div>
{% endblock %}

forum/templates/topics/post.html
{% extends 'base.html' %}

<title>{% block title %}Пост{% endblock %}</title>

{% block content %}
<br>
<form action = "{% url 'topics:create_post' %}" method ="POST">
	{% csrf_token %}
	<input type="text" class="form-control"  required placeholder="Название" name="title"><br>
	<textarea name="text" style = "height: 300px;" class="form-control" placeholder="Текст публикации" ></textarea>
	<br>
		<div class="btn-group btn-group-toggle" data-toggle="buttons">
		  <label class="btn btn-secondary">
			<input type="radio" name="options" id="option1" autocomplete="off" value="МГУПП"> МГУПП
		  </label>
		  <label class="btn btn-secondary">
			<input type="radio" name="options" id="option2" autocomplete="off" value="Образование"> Образование
		  </label>
		  <label class="btn btn-secondary active">
			<input type="radio" name="options" id="option3" autocomplete="off" value="ФЛУД"> ФЛУД
		  </label>
		</div>

	<div>
		<br>
	<button type="submit" class="btn btn-primary form-control">Отправить</button>
	</div>
</form>
{% endblock %}